baseURL: "https://ljukkti.github.io/sorali-codex" 
title: Laws of Soralae
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags
    subtags: subtags

menu:
    main:
        - name: Bills
          url: bills/
          weight: 1
        - name: Laws
          url: laws/
          weight: 2
        - name: Papers
          url: papers/
          weight: 3
        - name: Courses
          url: courses/
          weight: 4
        - name: Data
          url: data/
          weight: 5
        - name: Books
          url: books/
          weight: 6
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 7

params:
    description: "Sorali Codex hosts every law of The Divine Realms of Soralae."
    author: Ljukkti and the team
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
# this one's for the archive tab
    MainSections: ["bills","laws","papers","courses","data","books"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Sorali Codex
          subtitle: "Sorali Codex hosts every law of *the Divine Realms of Soralae*. In this compendium you will find all active, amended and rejected bills. It includes work of all jurisdictions and all governmental bodies of it is a *Citizenry vote*, *Senate Bill*, *High Council Decision* or *Imperial Decree*. <line break> The website is maintained by the third Yvalnos, imperial regent, Morimoto Chifu."
          imageUrl: "sorali square.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Senate Bills
              url: bills/
            - name: Laws in Effect
              url: laws/
            - name: Data
              url: data/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:@gmail.com
        - name: Discord
          url: https://discord.gg/soralae
        - name: Location
          url: location/
        - name: Open sessions
          url: opensessions/
        - name: GitHub
          url: https://github.com/Ljukkti

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "label text icon config yml"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2